export const jobs = [
    {
        id: 1,
        title: "Software Engineer",
        company: "Tech Company",
        location: "New York, NY",
        description: "Develop and maintain software applications.",
        salary: "$100,000 - $120,000",
        datePosted: "2023-10-01",
        jobType: "On-site",
    },
    {
        id: 2,
        title: "Data Analyst",
        company: "Data Corp",
        location: "San Francisco, CA",
        description: "Analyze data and generate reports.",
        salary: "$80,000 - $100,000",
        datePosted: "2023-09-15",
        jobType: "Hybrid",
    },
    {
        id: 3,
        title: "Product Manager",
        company: "Product Inc.",
        location: "Remote",
        description: "Lead product development and strategy.",
        salary: "$120,000 - $150,000",
        datePosted: "2023-08-20",
        jobType: "Remote",
    },
    {
        id: 4,
        title: "UX Designer",
        company: "Design Studio",
        location: "Austin, TX",
        description: "Create user-friendly designs and prototypes.",
        salary: "$90,000 - $110,000",
        datePosted: "2023-07-10",
        jobType: "On-site",
    },
    {
        id: 5,
        title: "Marketing Specialist",
        company: "Marketing Agency",
        location: "Chicago, IL",
        description: "Develop and execute marketing campaigns.",
        salary: "$70,000 - $90,000",
        datePosted: "2023-06-05",
        jobType: "Hybrid",
    },
    {
        id: 6,
        title: "Sales Executive",
        company: "Sales Co.",
        location: "Los Angeles, CA",
        description: "Drive sales and build client relationships.",
        salary: "$60,000 - $80,000",
        datePosted: "2023-05-15",
        jobType: "On-site",
    },
    {
        id: 7,
        title: "Web Developer",
        company: "Web Solutions",
        location: "Seattle, WA",
        description: "Build and maintain websites.",
        salary: "$70,000 - $90,000",
        datePosted: "2023-04-25",
        jobType: "Remote",
    },
    {
        id: 8,
        title: "System Administrator",
        company: "IT Services",
        location: "Boston, MA",
        description: "Manage and maintain IT systems.",
        salary: "$80,000 - $100,000",
        datePosted: "2023-03-30",
        jobType: "On-site",
    },
    {
        id: 9,
        title: "Graphic Designer",
        company: "Creative Agency",
        location: "Miami, FL",
        description: "Design graphics and visual content.",
        salary: "$50,000 - $70,000",
        datePosted: "2023-02-20",
        jobType: "Remote",
    },
    {
        id: 10,
        title: "Network Engineer",
        company: "Networking Solutions",
        location: "Denver, CO",
        description: "Design and implement network solutions.",
        salary: "$90,000 - $110,000",
        datePosted: "2023-01-10",
        jobType: "On-site",
    },
    {
        id: 11,
        title: "Content Writer",
        company: "Content Agency",
        location: "Remote",
        description: "Create and edit written content.",
        salary: "$40,000 - $60,000",
        datePosted: "2023-12-01",
        jobType: "Remote",
    },
    {
        id: 12,
        title: "Database Administrator",
        company: "Data Solutions",
        location: "Houston, TX",
        description: "Manage and maintain databases.",
        salary: "$80,000 - $100,000",
        datePosted: "2023-11-15",
        jobType: "Hybrid",
    },
    {
        id: 13,
        title: "DevOps Engineer",
        company: "Cloud Services",
        location: "San Diego, CA",
        description: "Implement DevOps practices and tools.",
        salary: "$100,000 - $120,000",
        datePosted: "2023-10-05",
        jobType: "On-site",
    },
    {
        id: 14,
        title: "SEO Specialist",
        company: "SEO Agency",
        location: "Remote",
        description: "Optimize websites for search engines.",
        salary: "$60,000 - $80,000",
        datePosted: "2023-09-25",
        jobType: "Remote",
    },
    {
        id: 15,
        title: "Project Manager",
        company: "Project Management Co.",
        location: "New York, NY",
        description: "Manage projects from start to finish.",
        salary: "$110,000 - $130,000",
        datePosted: "2023-08-15",
        jobType: "Hybrid",
    },
    {
        id: 16,
        title: "Business Analyst",
        company: "Business Solutions",
        location: "Chicago, IL",
        description: "Analyze business processes and requirements.",
        salary: "$70,000 - $90,000",
        datePosted: "2023-07-05",
        jobType: "On-site",
    },
    {
        id: 17,
        title: "Mobile Developer",
        company: "Mobile Apps Inc.",
        location: "Austin, TX",
        description: "Develop mobile applications for iOS and Android.",
        salary: "$90,000 - $110,000",
        datePosted: "2023-06-20",
        jobType: "Hybrid",
    },
    {
        id: 18,
        title: "Cybersecurity Analyst",
        company: "Security Solutions",
        location: "Remote",
        description: "Protect systems and networks from cyber threats.",
        salary: "$100,000 - $120,000",
        datePosted: "2023-05-10",
        jobType: "Remote",
    },
    {
        id: 19,
        title: "Cloud Engineer",
        company: "Cloud Technologies",
        location: "Seattle, WA",
        description: "Design and manage cloud infrastructure.",
        salary: "$110,000 - $130,000",
        datePosted: "2023-04-15",
        jobType: "Hybrid",
    },
    {
        id: 20,
        title: "Technical Writer",
        company: "Tech Writing Co.",
        location: "Remote",
        description: "Create technical documentation and manuals.",
        salary: "$50,000 - $70,000",
        datePosted: "2023-03-01",
        jobType: "Remote",
    },
];
